...@../DefaultVars

Title: {
    label: |md
        # Script Writing Overview
    |
    shape: text
    near: top-center
}

ScriptWriting: "Script Writing" {
    "Write Final Script for Episode/Movie"
}
