...@DefaultVars

direction: right

"Pre-Production" {
    "Writing" -> "Storyboard"
}

"Pre-Production"."Storyboard" -> "Production"."Layout"

"Production" {
    "Layout"

    "Layout" -> "Key Animation" -> "Inbetween Animation" -> "Coloring"
    "Layout" -> "3D Animation"
    "Layout" -> "Backgrounds"

    "Coloring" -> "Compositing"
    "3D Animation" -> "Compositing"
    "Backgrounds" -> "Compositing"

    "Compositing"
}

"Production"."Compositing" -> "Post-Production"."Video Editing"

"Post-Production" {
    "Audio" {
        "SFX"
        "Voice"
        "Music"
    }

    "Audio" -> "Video Editing"

    "Video Editing"
}
