...@DefaultVars

Title: {
    label: |md
        # Assets to Compositing
    |
    shape: text
    near: top-center
}

AssetsToCompositing: "Assets to Compositing" {
    "Sync Animtion Cels to Compositing Software" {
        "Export XDTS File" -> "Import XDTS File Into Compositing Software" -> BulkAddCelsToTimeline
        "Bulk Export Animation Cels" -> "Import Cels Into Compositing Software" -> BulkAddCelsToTimeline

        BulkAddCelsToTimeline: "Bulk Add Cels to Timeline,\n\nUsing Imported Timesheet Positions and Exposure Lengths"
    }
}
