...@DefaultVars

Title: {
    label: |md
        # Cut Compositing
    |
    shape: text
    near: top-center
}

CutCompositing: "Cut Compositing" {
    ImplementCameraWork: "Implement Camera Work,\n\nAs Instructed by Direction Memos on Timesheet\n" {
        "Main Camera"
        "Cels"
        "Books"
        "BGs"
    }

    ImplementCameraWork -> RenderCut

    RenderCut: "Render Cut" {
        RenderCut: "Render to Output Artifact"
    }
}
