classes: {
    RerouteNode {
        label: ""
        shape: circle
        width: 1
        height: 1
        style: {
            stroke: transparent
            fill: transparent
        }
    }
}
