...@DefaultVars

...@AssetProduction/Overview
...@AssetsToCompositing/Overview
...@CompositingCuts/Overview

direction: right

Title: {
    label: |md
        # Overview
    |
    shape: text
    near: top-center
}

AssetProduction.KeyAnimation -> AssetsToCompositing -> CompositingCuts

CompositingCuts.RenderingEngine.RenderCut -> Editorial.JoiningCuts

AudioAssets: "Audio Assets" {
    "SFX"
    "Voice"
    "Music"
}

AudioAssets -> Editorial.AudioPlacement

Editorial: {
    JoiningCuts: "Joining Cuts"
    Transitions: "Between-Cut Transitions"
    AudioPlacement: "Audio Placement"
    EditorialLevelAdditions: "Editorial-Level Additions"

    JoiningCuts -> Transitions
    Transitions -> FinalPictureRender
    AudioPlacement -> FinalPictureRender
    EditorialLevelAdditions -> FinalPictureRender

    FinalPictureRender: "Final Picture Render"
}

Editorial.FinalPictureRender -> PictureLock

PictureLock: "Picture Lock"

PictureLock -> SoundEditing

AudioAssets -> SoundEditing

SoundEditing: "Sound Editing" {
    "Finish Audio Work" -> "Final Audio Mixing" -> "Final Mastering"
}

SoundEditing -> Delivery

Delivery {
    MasterVideoFiles: "Create Master Video Files\n\n(Combining Picture and Sound)"
}

Delivery -> Distribution

Distribution {
}
