...@DefaultVars

PreProduction: "Pre-Production" {
    Ideas: @Ideas/Overview.Ideas
    Writing: @Writing/Overview.Writing
    Storyboarding: @Storyboarding/Overview.Storyboarding
    Design: @Design/Overview.Design
}

Production: "Production" {
    AssetProduction: @AssetProduction/Overview.AssetProduction
    AssetsToCompositing: @AssetsToCompositing/Overview.AssetsToCompositing
    CompositingCuts: @CompositingCuts/Overview.CompositingCuts
}

PostProduction: "Post-Production" {
    Editorial: @Editorial/Overview.Editorial
    SoundEditing: @SoundEditing/Overview.SoundEditing
}

Delivery: @Delivery/Overview.Delivery

direction: right

Title: {
    label: |md
        # Overview
    |
    shape: text
    near: top-center
}

PreProduction {
    Ideas -> Writing -> Storyboarding -> Design
}

PreProduction.Design -> Production.AssetProduction

Production {
    AssetProduction.KeyAnimation -> AssetsToCompositing -> CompositingCuts
}

Production.CompositingCuts.RenderingEngine.RenderCut -> PostProduction.Editorial.JoiningCuts

Production.AssetProduction.Audio -> PostProduction.Editorial.AudioPlacement

PostProduction {
    Editorial.FinalPictureRender -> PictureLock

    PictureLock: "Picture Lock"

    PictureLock -> SoundEditing
}

Production.AssetProduction.Audio -> PostProduction.SoundEditing

PostProduction.SoundEditing -> Delivery -> Distribution

Distribution {
}
