...@../DefaultVars

Title: {
    label: |md
        # Compositing Work
    |
    shape: text
    near: top-center
}

CompositingCuts.CompositingWork: "Compositing Work" {
    ImplementCameraWork: "Implement Camera Work,\n\nAs Instructed by Direction Memos on Timesheet\n" {
        "Main Camera"
        "Cels"
        "Books"
        "BGs"
    }

    RoughAudio: "Rough Audio"
}
