...@../DefaultVars

...@CompositingCuts
...@CompositingToRendering
...@RenderingEngine

Title: {
    label: |md
        # Compositing Cuts Overview
    |
    shape: text
    near: top-center
}

CompositingCuts -> CompositingToRendering -> RenderingEngine
