...@../DefaultVars

...@CompositingWork
...@CompositingToRendering
...@RenderingEngine

Title: {
    label: |md
        # Compositing Cuts Overview
    |
    shape: text
    near: top-center
}

CompositingCuts: "Compositing Cuts" {
    CompositingWork -> CompositingToRendering -> RenderingEngine
}
