...@../DefaultVars

Title: {
    label: |md
        # Design Overview
    |
    shape: text
    near: top-center
}

Design: "Design" {
    "Character Design"
    "Color Design"
    "Background Design (Art Director)"
    "Prop Design"
    "Other"
}
