...@../DefaultVars

...@CutCompositing
...@CompositingToRendering
...@RenderingEngine

direction: right

Title: {
    label: |md
        # Cut Compositing Overview
    |
    shape: text
    near: top-center
}

CutCompositing -> CompositingToRendering -> RenderingEngine
