...@../DefaultVars

Title: {
    label: |md
        # Pre-Production Ideas Overview
    |
    shape: text
    near: top-center
}

PreProductionIdeas: "Ideas" {
    "Gathering Ideas"
    "Gathering Staff"
}
