...@../DefaultVars

Title: {
    label: |md
        # Sound Editing Overview
    |
    shape: text
    near: top-center
}

SoundEditing: "Sound Editing" {
    "Finish Audio Work" -> "Final Audio Mixing" -> "Final Mastering"
}
