...@../DefaultVars

...@../D2Utils

Title: {
    label: |md
        # 3D Asset Creation
    |
    shape: text
    near: top-center
}

AssetProduction.3dAssetCreation: "3D Asset Creation" {

    Modeling: "Modeling" {
        FullResSculping: "Full-Res Sculping"

        FullResSculping -> Retopologize

        Retopologize: "Retopologize"

        Retopologize -> UvUnwrapping

        PolyModeling: "Poly Modeling"

        PolyModeling -> UvUnwrapping

        UvUnwrapping: "UV Unwrapping"
    }

    Modeling -- ModelingRerouteNodeOutgoingA

    ModelingRerouteNodeOutgoingA {
        class: RerouteNode
    }

    ModelingRerouteNodeOutgoingA -> AuthorMaterials
    ModelingRerouteNodeOutgoingA -> Rigging

    AuthorMaterials: "Author Materials" {
        "Texturing"
        "Adjusting UVs if Needed"
        "Custom Shaders"
    }

    Rigging: "Rigging" {
        "Skinning / Weight Painting"
        "Author Corrective Blend Shapes / Shape Keys / Morph Targets"
    }
}
