...@../DefaultVars

Title: {
    label: |md
        # Backgrounds
    |
    shape: text
    near: top-center
}

AssetProduction.Backgrounds: "Backgrounds" {
    "Author Background Art"
    "Author Book Elements\n\n(Non-Animated Elements; E.g., BG Cutouts)"
}
