...@../DefaultVars

...@../D2Utils

Title: {
    label: |md
        # Curve-Driven (Interpolated) Animation
    |
    shape: text
    near: top-center
}

AssetProduction.CurveDrivenAnimation: "Curve-Driven (Interpolated) Animation" {
    AuthoringAnimationAssets: "Authoring Animation Assets" {
        "Key-Framing Bone Transforms"
        "Animating Curve Data" {
            "Material Parameters"
            "Blend Shape Values"
            "Custom Properties"
        }
    }

    "Authoring Custom Blend Shapes / Shape Keys / Morph Targets"
}
