...@../DefaultVars

Title: {
    label: |md
        # Layout
    |
    shape: text
    near: top-center
}

AssetProduction.Layout: "Layout / Rough Animation" {
    "Draft the Composition\n\n(Characters, Set Dressing, Etc.)"
    # If the layout artist is going to clean up his own rough keys frames, it's called rough genga.
    # If a dedicated artist will be the one to clean up these rough keys frames, it's called 1st key animation (ichigen).
    "Draft the Key Frames (Rough Genga, or 1st Key Iteration (Ichigen))"
    "Fill Out Timesheet" {
        "Compositing Instructions"
        "Camera Instructions"
        "Decide the Timing of Key Frames"
        "Decide the Number of / Timing of Inbetweens (on 1s, on 2s, on 3s)"
    }
}
