...@../DefaultVars

...@../D2Utils

...@Layout
...@TimesheetDrivenAnimation
...@CurveDrivenAnimation
...@Backgrounds
...@3dAssetCreation
...@Audio

Title: {
    label: |md
        # Asset Production Overview
    |
    shape: text
    near: top-center
}

AssetProduction: "Asset Production" {

    Layout -> LayoutDirectorRevisions

    LayoutDirectorRevisions: "Directors Revise Layout"

    LayoutDirectorRevisions -- LayoutDirectorRevisionsRerouteNodeOutgoingA

    LayoutDirectorRevisionsRerouteNodeOutgoingA: {
        class: RerouteNode
    }

    LayoutDirectorRevisionsRerouteNodeOutgoingA -> TimesheetDrivenAnimation.KeyAnimation
    LayoutDirectorRevisionsRerouteNodeOutgoingA -> CurveDrivenAnimation
    LayoutDirectorRevisionsRerouteNodeOutgoingA -> Backgrounds
}
