...@../DefaultVars

Title: {
    label: |md
        # Asset Production Overview
    |
    shape: text
    near: top-center
}

AssetProduction: "Asset Production" {
    KeyAnimation: "Key Animation" {
        "Author the Key Frames"
        "Decide the Timing and Number of Inbetweens"
    }
}
