...@../DefaultVars

...@../D2Utils

...@Layout
...@3dAssetProduction
...@2dAssetProduction
...@Backgrounds
...@Audio

Title: {
    label: |md
        # Asset Production Overview
    |
    shape: text
    near: top-center
}

AssetProduction: "Asset Production" {

    Layout -> LayoutDirectorRevisions

    LayoutDirectorRevisions: "Directors Revise Layout"

    LayoutDirectorRevisions -- LayoutDirectorRevisionsRerouteNodeOutgoingA

    LayoutDirectorRevisionsRerouteNodeOutgoingA: {
        class: RerouteNode
    }

    LayoutDirectorRevisionsRerouteNodeOutgoingA -> 3dAssetProduction
    LayoutDirectorRevisionsRerouteNodeOutgoingA -> 2dAssetProduction.KeyAnimation
    LayoutDirectorRevisionsRerouteNodeOutgoingA -> Backgrounds
}
