...@../DefaultVars

Title: {
    label: |md
        # Delivery Overview
    |
    shape: text
    near: top-center
}

Delivery {
    MasterVideoFiles: "Create Master Video Files\n\n(Combining Picture and Sound)"
}
